### ISSUE TITLE
External Participants - Google Chat/Absolute Poll

### ISSUE THREAD

**Issue by DeltaEtaEta** [dyaskur/google-chat-poll#69] opened 2024-03-24 18:37 UTC
I have external participants in Google Chat/Spaces. They are unable to participate in Absolute Polls when we post. Can the Absolute Poll app be used by external members? If so, is there a permission that needs to be given?

**Comment by dyaskur** [comment] 2024-03-25 06:47
Thank you for bringing this to our attention. It appears that this issue is a duplicate of #18 and has also been replicated by #43 and #24.

The problem stems from Google itself, rather than the application.

To expedite progress, please consider casting your vote at https://issuetracker.google.com/issues/297141187. Your contribution may help accelerate the resolution process.

**Closed by dyaskur** 2024-03-25 06:47 UTC
Labels: duplicate
